#!/usr/bin/env bash

function get_brightness {
    brightnessctl -l | grep '%' | head -n 1 | cut -d '(' -f 2 | cut -d ')' -f 1 | cut -d '%' -f 1
}

function send_notification {
    brightness=`get_brightness`

    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character

    bar=$(seq -s "─" $(($brightness / 5)) | sed 's/[0-9]//g')

    # Send the notification
    dunstify -t 5000 -i computer-laptop -r 2593 -u normal "$brightness  $bar"

}

case $1 in
    up)
        brightnessctl set +5%
		send_notification
	;;
    down)
        brightnessctl set 5%-
    	send_notification
	;;
esac

