#!/usr/bin/env bash

get_volume() {
    vol=$(amixer sget Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1) 
}

is_mute() {
    status=$(amixer sget Master | grep '%' | grep -oE '[^ ]+$' | grep off)
}

icon() {
    get_volume
    is_mute
    
    if [[ $vol == 0 || $status ]]; then 
        echo "婢 muted"
    
    elif [[ $vol < 20 ]]; then
        echo "奄 $vol"
        
    elif [[ $vol < 60 ]]; then
        echo "奔 $vol"
    
    else 
        echo "墳 $vol"
        
    fi
}

update() {
    get_volume
    is_mute
    
    if [[ $status ]]; then
        eww update vol_level="0"
    
    else
        eww update vol_level="$vol"
    
    fi

    # vol_with_icon refers to the button on the bar which displays the info
    vol_with_icon=`icon`
    eww update vol_with_icon="$vol_with_icon"
}

if [[ "$1" == "up" ]]; then
    amixer sset Master 5%+

elif [[ "$1" == "down" ]]; then
    amixer sset Master 5%-

elif [[ "$1" == "set" ]]; then
    amixer sset Master "$2"%
    update

elif [[ "$1" == "mute" ]]; then
    amixer  sset Master toggle

elif [[ "$1" == "update" ]]; then
    update
        
elif [[ "$1" == "icon" ]]; then 
    icon

else
    get_volume
    echo "$vol"

fi
